import { ArrowUpRight, Compass, HeartHandshake, MapPinned, ShieldCheck } from 'lucide-react';
import { WebsiteCMSSettings } from '../types';
import { resolveBusinessProfile } from '../utils/businessProfile';

interface AboutViewProps { websiteCMS?: WebsiteCMSSettings; }

export default function AboutView({ websiteCMS }: AboutViewProps) {
  const business = resolveBusinessProfile(websiteCMS);
  return <div id="about-view" className="pravaah-page pravaah-about-page"><section className="pravaah-page-hero pravaah-page-hero--about"><div className="pravaah-page-hero__image"><img src="/images/roopkund/why-ground-team.jpg" alt="A Pravaah travel team in the Himalaya" /></div><div className="pravaah-page-hero__veil" /><div className="pravaah-shell pravaah-page-hero__inner"><span className="pravaah-kicker pravaah-kicker--light">About {business.companyName}</span><h1>Travel is better<br /><em>when it stays human.</em></h1><p>{business.tagline}</p></div></section><section className="pravaah-about-manifesto pravaah-section"><div className="pravaah-shell pravaah-about-manifesto__grid"><span className="pravaah-kicker">What we believe</span><h2>Good travel is a conversation with a place.</h2><div><p>Pravaah is a travel company shaped around the Himalayan way of moving: attentive, local, and unhurried. We make space for the details that turn a route into a memory.</p><p>From our base in {business.address}, we help travellers find the right balance of comfort, curiosity, and time.</p></div></div></section><section className="pravaah-about-principles pravaah-section"><div className="pravaah-shell"><div className="pravaah-section-heading"><div><span className="pravaah-kicker">The way we work</span><h2>Care is part of the itinerary.</h2></div></div><div className="pravaah-principles">{[{ icon: MapPinned, title: 'Know the ground', copy: 'Routes are shaped by local knowledge, lived conditions, and the realities of the landscape.' }, { icon: HeartHandshake, title: 'Make it personal', copy: 'We listen first, then build a journey around your pace, people, and reason for going.' }, { icon: ShieldCheck, title: 'Hold the details', copy: 'Clear planning, thoughtful support, and a real person when the weather changes.' }].map(({ icon: Icon, title, copy }, index) => <article key={title}><span>0{index + 1}</span><Icon className="h-5 w-5" aria-hidden="true" /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="pravaah-about-contact"><div className="pravaah-shell"><Compass className="h-6 w-6" aria-hidden="true" /><p>Planning a journey from {business.address}? We would love to hear what is drawing you there.</p><a href={`mailto:${business.email}`}>Write to the travel desk <ArrowUpRight className="h-4 w-4" aria-hidden="true" /></a></div></section></div>;
}
