import { useMemo, useState } from 'react';
import { ArrowUpRight, BookOpen, Search } from 'lucide-react';
import { BlogPost } from '../types';
import { getTravelImage, handleTravelImageError } from '../utils/imageFallback';

interface BlogsViewProps { blogPosts: BlogPost[]; onNavigate: (view: string, packageId?: string | null) => void; loading: boolean; }
const excerpt = (content: string) => String(content || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim().slice(0, 180);

export default function BlogsView({ blogPosts, onNavigate, loading }: BlogsViewProps) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const categories = useMemo(() => ['All', ...Array.from(new Set(blogPosts.map((post) => post.category).filter(Boolean)))], [blogPosts]);
  const posts = useMemo(() => blogPosts.filter((post) => (category === 'All' || post.category === category) && (!query.trim() || `${post.title} ${post.category} ${post.content}`.toLowerCase().includes(query.toLowerCase()))), [blogPosts, category, query]);
  const lead = posts[0];
  const open = (post: BlogPost) => onNavigate('blog-detail', post.slug || post.id);

  return <div id="blogs-view" className="pravaah-page pravaah-blog-page"><section className="pravaah-page-hero pravaah-page-hero--journal"><div className="pravaah-page-hero__image"><img src={getTravelImage(lead?.featuredImageUrl || '/images/roopkund/rishikesh-valley.jpg')} alt="A Pravaah field journal" onError={handleTravelImageError} /></div><div className="pravaah-page-hero__veil" /><div className="pravaah-shell pravaah-page-hero__inner"><span className="pravaah-kicker pravaah-kicker--light">The Pravaah journal</span><h1>Stories from<br /><em>the long way round.</em></h1><p>Notes on landscapes, local life, and travelling with enough time to notice both.</p></div></section><section className="pravaah-blog-body pravaah-section"><div className="pravaah-shell"><div className="pravaah-blog-toolbar"><div><span className="pravaah-kicker">Read slowly</span><p>{posts.length} notes in the archive</p></div><div className="pravaah-blog-controls"><label><Search className="h-4 w-4" aria-hidden="true" /><span className="sr-only">Search journal</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the journal" /></label><div>{categories.map((item) => <button type="button" key={item} className={category === item ? 'is-active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></div></div>{loading ? <div className="pravaah-blog-loading">Loading the journal...</div> : posts.length === 0 ? <div className="pravaah-empty-state pravaah-empty-state--large"><BookOpen className="h-7 w-7" aria-hidden="true" /><h2>No notes match that search.</h2><p>Try another word or return to the full archive.</p></div> : <div className="pravaah-blog-index"><article className="pravaah-blog-lead"><button type="button" onClick={() => open(lead)}><img src={getTravelImage(lead.featuredImageUrl)} alt={lead.title} onError={handleTravelImageError} /></button><div><span className="pravaah-kicker">{lead.category}</span><h2>{lead.title}</h2><p>{excerpt(lead.content)}</p><button type="button" className="pravaah-text-link" onClick={() => open(lead)}>Read the story <ArrowUpRight className="h-4 w-4" aria-hidden="true" /></button></div></article><div className="pravaah-blog-list">{posts.slice(1).map((post, index) => <article key={post.id}><span className="pravaah-blog-list__number">{String(index + 2).padStart(2, '0')}</span><div className="pravaah-blog-list__image">{post.featuredImageUrl && <img src={getTravelImage(post.featuredImageUrl)} alt="" loading="lazy" onError={handleTravelImageError} />}</div><div><span className="pravaah-kicker">{post.category}</span><h3><button type="button" onClick={() => open(post)}>{post.title}</button></h3><p>{excerpt(post.content)}</p><small>{post.author || 'Pravaah field desk'}</small></div><button type="button" className="pravaah-list-arrow" onClick={() => open(post)} aria-label={`Read ${post.title}`}><ArrowUpRight className="h-4 w-4" aria-hidden="true" /></button></article>)}</div></div>}</div></section></div>;
}
