import { useState } from 'react';
import { ArrowUpRight, CalendarDays, Clock3, Mail, MapPin, Phone, Send } from 'lucide-react';
import { WebsiteCMSSettings } from '../types';
import { resolveBusinessProfile } from '../utils/businessProfile';
import PremiumEnquiryModal from './PremiumEnquiryModal';

interface ContactViewProps { onEnquirySuccess: () => void; websiteCMS: WebsiteCMSSettings; }

export default function ContactView({ onEnquirySuccess, websiteCMS }: ContactViewProps) {
  const [enquiryOpen, setEnquiryOpen] = useState(false);
  const business = resolveBusinessProfile(websiteCMS);
  const hours = business.workingHours ? [business.workingHours] : [];
  return <div id="contact-view" className="pravaah-page pravaah-contact-page"><section className="pravaah-contact-hero"><div className="pravaah-shell"><span className="pravaah-kicker pravaah-kicker--light">The travel desk</span><h1>Let the first step<br /><em>be a conversation.</em></h1><p>Tell us what is pulling you out there. We will help you find the shape of the journey.</p><button type="button" className="pravaah-button pravaah-button--copper" onClick={() => setEnquiryOpen(true)}>Start an enquiry <Send className="h-4 w-4" aria-hidden="true" /></button></div></section><section className="pravaah-contact-body pravaah-section"><div className="pravaah-shell pravaah-contact-grid"><div className="pravaah-contact-info"><span className="pravaah-kicker">Find us here</span><h2>Close to the mountains,<br />close to the details.</h2><div className="pravaah-contact-details"><a href={`mailto:${business.email}`}><Mail className="h-5 w-5" aria-hidden="true" /><span><small>Email</small>{business.email}</span><ArrowUpRight className="h-4 w-4" aria-hidden="true" /></a><a href={business.phoneHref}><Phone className="h-5 w-5" aria-hidden="true" /><span><small>Call the desk</small>{business.phone}</span><ArrowUpRight className="h-4 w-4" aria-hidden="true" /></a><div><MapPin className="h-5 w-5" aria-hidden="true" /><span><small>Our office</small>{business.address}</span></div></div></div><div className="pravaah-contact-card"><span className="pravaah-kicker">What happens next</span><h2>A clear first draft,<br />within a human conversation.</h2><ol><li><span>01</span><p>We listen to the feeling behind the trip.</p></li><li><span>02</span><p>We suggest a route, pace, and way through.</p></li><li><span>03</span><p>We refine the details until it feels like yours.</p></li></ol><button type="button" className="pravaah-text-link" onClick={() => setEnquiryOpen(true)}>Open the enquiry form <ArrowUpRight className="h-4 w-4" aria-hidden="true" /></button></div></div></section><section className="pravaah-contact-hours"><div className="pravaah-shell"><div><Clock3 className="h-5 w-5" aria-hidden="true" /><span className="pravaah-kicker pravaah-kicker--light">Travel desk hours</span></div><div>{hours.length > 0 ? hours.map((hour, index) => <p key={`${hour}-${index}`}>{hour}</p>) : <p>We reply as soon as the travel desk is back online.</p>}</div><div><CalendarDays className="h-5 w-5" aria-hidden="true" /><p>Based in {business.address}</p></div></div></section><PremiumEnquiryModal isOpen={enquiryOpen} onClose={() => setEnquiryOpen(false)} onSuccess={onEnquirySuccess} /></div>;
}
