import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Search, X } from 'lucide-react';
import { TravelPackage } from '../types';
import { getTravelImage, handleTravelImageError } from '../utils/imageFallback';
import { openPackage } from '../utils/packageRoute';

interface GlobalSearchProps { packages: TravelPackage[]; onNavigate: (view: string, packageId?: string | null) => void; onClose: () => void; isClosing?: boolean; }

export default function GlobalSearch({ packages, onNavigate, onClose, isClosing = false }: GlobalSearchProps) {
  const [query, setQuery] = useState('');
  useEffect(() => { const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; document.addEventListener('keydown', handleKey); return () => { document.body.style.overflow = previous; document.removeEventListener('keydown', handleKey); }; }, [onClose]);
  const results = useMemo(() => { const normalized = query.trim().toLowerCase(); if (!normalized) return []; return packages.filter((pkg) => pkg.active !== false && [pkg.title, pkg.destination, pkg.category, pkg.location].some((field) => String(field || '').toLowerCase().includes(normalized))).slice(0, 8); }, [packages, query]);
  return <div className={`pravaah-search-overlay ${isClosing ? 'is-closing' : 'is-open'}`} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="pravaah-search-dialog" role="dialog" aria-modal="true" aria-label="Search journeys and destinations"><div className="pravaah-search-dialog__heading"><div><span className="pravaah-kicker">The route finder</span><h2>Where would you like to go?</h2></div><button type="button" className="pravaah-icon-button" onClick={onClose} aria-label="Close search"><X className="h-5 w-5" aria-hidden="true" /></button></div><label className="pravaah-search-input"><Search className="h-5 w-5" aria-hidden="true" /><span className="sr-only">Search packages and destinations</span><input autoFocus={!isClosing} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try Ladakh, pilgrimage, valley..." /></label><div className="pravaah-search-results">{!query.trim() ? <p className="pravaah-search-empty">Start with a place, a feeling, or a route.</p> : results.length === 0 ? <p className="pravaah-search-empty">No published journeys match &quot;{query}&quot;.</p> : results.map((pkg) => <button type="button" key={pkg.id} className="pravaah-search-result" onClick={() => { openPackage(onNavigate, pkg); onClose(); }}><img src={getTravelImage(pkg.imageUrl || pkg.heroImage || '/images/buran-ghati/hero-buran-ghati.webp')} alt="" onError={handleTravelImageError} /><span><small>{pkg.category} / {pkg.location}</small><strong>{pkg.title}</strong><em>{pkg.duration} <ArrowUpRight className="h-4 w-4" aria-hidden="true" /></em></span></button>)}</div></div></div>;
}
