name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - run: npm install -g firebase-tools

run: firebase deploy --project zealous-theory-q09p9 --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"